# ????????? ???? ?????? H2
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notebook
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
