spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notebook
    driverClassName: org.postgresql.Driver
    username: notebook_admin
    password: secret
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: never
