CREATE TABLE account
(
    account_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(50),
    last_name  VARCHAR(50),
    email      VARCHAR(100),
    password   VARCHAR(50),
    login      VARCHAR(50),
    phone      VARCHAR(10),
    CONSTRAINT pk_account PRIMARY KEY (account_id)
);

CREATE TABLE account_note
(
    account_id BIGINT NOT NULL,
    note_id    BIGINT NOT NULL
);

CREATE TABLE contact_info
(
    contact_info_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(50),
    type            VARCHAR(20),
    CONSTRAINT pk_contact_info PRIMARY KEY (contact_info_id)
);

CREATE TABLE note
(
    note_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name  VARCHAR(50)                             NOT NULL,
    last_name   VARCHAR(50)                             NOT NULL,
    second_name VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_note PRIMARY KEY (note_id)
);

CREATE TABLE contact_info_id
(
    note_id         BIGINT NOT NULL,
    contact_info_id BIGINT NOT NULL
);

CREATE TABLE note_tips
(
    note_id BIGINT NOT NULL,
    tips_id BIGINT NOT NULL
);

CREATE TABLE tips
(
    tips_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title   VARCHAR(30),
    content TEXT,
    CONSTRAINT pk_tips PRIMARY KEY (tips_id)
);

CREATE TABLE type_tips_info
(
    type_tips_info_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name              VARCHAR(255),
    account_id        BIGINT,
    CONSTRAINT pk_type_tips_info PRIMARY KEY (type_tips_info_id)
);

ALTER TABLE account_note
    ADD CONSTRAINT uc_account_note_entities_note UNIQUE (note_id);

ALTER TABLE note_tips
    ADD CONSTRAINT uc_note_tips_tips_tips UNIQUE (tips_id);

ALTER TABLE type_tips_info
    ADD CONSTRAINT FK_TYPE_TIPS_INFO_ON_OWNER_ACCOUNT FOREIGN KEY (account_id) REFERENCES account (account_id);

ALTER TABLE account_note
    ADD CONSTRAINT fk_note_account FOREIGN KEY (account_id) REFERENCES account (account_id);

ALTER TABLE account_note
    ADD CONSTRAINT fk_account_note FOREIGN KEY (note_id) REFERENCES note (note_id);

ALTER TABLE note_tips
    ADD CONSTRAINT fk_note_tips_on_note FOREIGN KEY (note_id) REFERENCES note (note_id);

ALTER TABLE note_tips
    ADD CONSTRAINT fk_note_tips_on_tips FOREIGN KEY (tips_id) REFERENCES tips (tips_id);

