CREATE TABLE account
(
    account_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(50),
    last_name  VARCHAR(50),
    email      VARCHAR(100),
    password   VARCHAR(50),
    login      VARCHAR(50),
    phone      VARCHAR(10),
    CONSTRAINT pk_account PRIMARY KEY (account_id)
);

CREATE TABLE account_note
(
    account_id BIGINT NOT NULL,
    note_id    BIGINT NOT NULL
);

CREATE TABLE contact_info
(
    contact_info_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(50),
    type            VARCHAR(20),
    account_id      BIGINT,
    CONSTRAINT pk_contact_info PRIMARY KEY (contact_info_id)
);

CREATE TABLE contact_info_type
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    account_id BIGINT,
    CONSTRAINT pk_contact_info_type PRIMARY KEY (id)
);


CREATE TABLE note
(
    note_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name  VARCHAR(50)                             NOT NULL,
    last_name   VARCHAR(50)                             NOT NULL,
    second_name VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_note PRIMARY KEY (note_id)
);

CREATE TABLE note_contact_info
(
    note_id         BIGINT NOT NULL,
    contact_info_id BIGINT NOT NULL
);

CREATE TABLE note_notices
(
    note_id   BIGINT NOT NULL,
    notice_id BIGINT NOT NULL
);

CREATE TABLE notice
(
    notice_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title     VARCHAR(30),
    content   TEXT,
    CONSTRAINT pk_tips PRIMARY KEY (notice_id)
);

CREATE TABLE notice_type_info
(
    notice_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255),
    account_id     BIGINT,
    CONSTRAINT pk_type_tips_info PRIMARY KEY (notice_type_id)
);

ALTER TABLE account_note
    ADD CONSTRAINT uc_account_note_id UNIQUE (note_id);

ALTER TABLE account_note
    ADD CONSTRAINT fk_note_on_account FOREIGN KEY (account_id) REFERENCES account (account_id);

ALTER TABLE account_note
    ADD CONSTRAINT fk_account_on_note FOREIGN KEY (note_id) REFERENCES note (note_id);

ALTER TABLE contact_info
    ADD CONSTRAINT fk_owner_account_id FOREIGN KEY (account_id) REFERENCES account (account_id);

ALTER TABLE contact_info_type
    ADD CONSTRAINT fk_owner_account_id FOREIGN KEY (account_id) REFERENCES account (account_id);

ALTER TABLE note_contact_info
    ADD CONSTRAINT uc_contact_info_id UNIQUE (contact_info_id);

ALTER TABLE note_contact_info
    ADD CONSTRAINT fk_note_contact_info_on_contact_info FOREIGN KEY (contact_info_id) REFERENCES contact_info (contact_info_id);

ALTER TABLE note_contact_info
    ADD CONSTRAINT fk_note_contact_info_on_note FOREIGN KEY (note_id) REFERENCES note (note_id);

ALTER TABLE note_notices
    ADD CONSTRAINT uc_note_tips_on_tips_notice UNIQUE (notice_id);

ALTER TABLE note_notices
    ADD CONSTRAINT fk_tips_on_note FOREIGN KEY (note_id) REFERENCES note (note_id);

ALTER TABLE note_notices
    ADD CONSTRAINT fk_tips_on_notice FOREIGN KEY (notice_id) REFERENCES notice (notice_id);

ALTER TABLE notice_type_info
    ADD CONSTRAINT fk_type_on_account FOREIGN KEY (account_id) REFERENCES account (account_id);