
CREATE TABLE account
(
    account_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    email      VARCHAR(255),
    password   VARCHAR(255),
    login      VARCHAR(255),
    phone      VARCHAR(255),
    position   VARCHAR(255),
    CONSTRAINT pk_account PRIMARY KEY (account_id)
);

CREATE TABLE account_note_entities
(
    account_account_id    BIGINT NOT NULL,
    note_entities_note_id BIGINT NOT NULL
);

CREATE TABLE contact_info
(
    contact_info_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(255),
    type            VARCHAR(255),
    CONSTRAINT pk_contact_info PRIMARY KEY (contact_info_id)
);

CREATE TABLE note
(
    note_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name  VARCHAR(255)                            NOT NULL,
    last_name   VARCHAR(255)                            NOT NULL,
    second_name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_note PRIMARY KEY (note_id)
);

CREATE TABLE note_addresses
(
    note_note_id              BIGINT NOT NULL,
    addresses_contact_info_id BIGINT NOT NULL
);

CREATE TABLE note_phones
(
    note_note_id           BIGINT NOT NULL,
    phones_contact_info_id BIGINT NOT NULL
);

CREATE TABLE note_tips
(
    note_note_id BIGINT NOT NULL,
    tips_tips_id BIGINT NOT NULL
);

CREATE TABLE tips
(
    tips_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title   VARCHAR(255),
    content VARCHAR(255),
    CONSTRAINT pk_tips PRIMARY KEY (tips_id)
);

CREATE TABLE type_tips_info
(
    type_tips_info_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name              VARCHAR(255),
    owner_account_id  BIGINT,
    CONSTRAINT pk_type_tips_info PRIMARY KEY (type_tips_info_id)
);

ALTER TABLE account_note_entities
    ADD CONSTRAINT uc_account_note_entities_noteentities_note UNIQUE (note_entities_note_id);

ALTER TABLE note_addresses
    ADD CONSTRAINT uc_note_addresses_addresses_contact_info UNIQUE (addresses_contact_info_id);

ALTER TABLE note_phones
    ADD CONSTRAINT uc_note_phones_phones_contact_info UNIQUE (phones_contact_info_id);

ALTER TABLE note_tips
    ADD CONSTRAINT uc_note_tips_tips_tips UNIQUE (tips_tips_id);

ALTER TABLE type_tips_info
    ADD CONSTRAINT FK_TYPE_TIPS_INFO_ON_OWNER_ACCOUNT FOREIGN KEY (owner_account_id) REFERENCES account (account_id);

ALTER TABLE account_note_entities
    ADD CONSTRAINT fk_accnotent_on_account FOREIGN KEY (account_account_id) REFERENCES account (account_id);

ALTER TABLE account_note_entities
    ADD CONSTRAINT fk_accnotent_on_note FOREIGN KEY (note_entities_note_id) REFERENCES note (note_id);

ALTER TABLE note_addresses
    ADD CONSTRAINT fk_notadd_on_contact_info FOREIGN KEY (addresses_contact_info_id) REFERENCES contact_info (contact_info_id);

ALTER TABLE note_addresses
    ADD CONSTRAINT fk_notadd_on_note FOREIGN KEY (note_note_id) REFERENCES note (note_id);

ALTER TABLE note_tips
    ADD CONSTRAINT fk_note_tips_on_note FOREIGN KEY (note_note_id) REFERENCES note (note_id);

ALTER TABLE note_tips
    ADD CONSTRAINT fk_note_tips_on_tips FOREIGN KEY (tips_tips_id) REFERENCES tips (tips_id);

ALTER TABLE note_phones
    ADD CONSTRAINT fk_notpho_on_contact_info FOREIGN KEY (phones_contact_info_id) REFERENCES contact_info (contact_info_id);

ALTER TABLE note_phones
    ADD CONSTRAINT fk_notpho_on_note FOREIGN KEY (note_note_id) REFERENCES note (note_id);